use_frameworks!

target 'mAVr_Example' do
  pod 'M3U8Kit2', :git => 'https://github.com/aikdong/M3U8Paser.git'
  pod 'mAVr', :path => '../'

  target 'mAVr_Tests' do
    inherit! :search_paths

    
  end
end
